name: Addon Release

on:
  release:
    types: [published]

jobs:
  prepare-pulsarlib:
    name: Prepare Pulsar Lib
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Pulsar-Dev/pulsar-lib
          ref: master
          submodules: recursive
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pulsarlib
          retention-days: 1
          path: |
            ./
            !.git/**
            !.github/**
            !pulsarlib.png
            !README.md

  prepare-gm-express:
    name: Prepare GM Express
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: CFC-Servers/gm_express
          ref: main
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gm_express
          retention-days: 1
          path: |
            ./**.lua
            !.git/**
            !.github/**

  prepare-pixel-ui:
    name: Prepare PIXEL UI
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Pulsar-Dev/pixel-ui
          ref: master
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pixel-ui
          retention-days: 1
          path: |
            ./**.lua
            !.git/**
            !.github/**

  release:
    name: Build Release ZIP
    needs: [prepare-pulsarlib, prepare-gm-express, prepare-pixel-ui]
    runs-on: ubuntu-22.04

    steps:
      - name: Download PulsarLib
        uses: actions/download-artifact@v2
        with:
          name: pulsarlib
          path: pulsar-lib

      - name: Download PIXEL-UI
        uses: actions/download-artifact@v2
        with:
          name: pixel-ui
          path: pulsar-lib/lua/pulsar_lib/modules/

      - name: Download GM Express
        uses: actions/download-artifact@v2
        with:
          name: gm_express
          path: pulsar-lib/lua/pulsar_lib/modules/

      - name: Create ZIP archive
        run: zip -r pulsar-lib.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pulsar-lib
          retention-days: 1
          path: pulsar-lib.zip
    
      - name: Upload ZIP to release
        uses: xresloader/upload-to-github-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            file: pulsar-lib.zip
            update_latest_release: true